Vipa\JournalBundle\Entity\ArticleFile:
    properties:
        type:
            - NotBlank: { groups: [submission], message: 'type.field.article.files.not.be.blank' }
        langCode:
            - NotBlank: { groups: [submission], message: 'language.field.article.files.not.be.blank' }
        title:
            - NotBlank: { groups: [submission], message: 'title.field.article.files.not.be.blank' }
        file:
            - NotBlank: { groups: [submission], message: 'file.field.article.files.not.be.blank' }