Ojs\JournalBundle\Entity\AuthorTranslation:
  properties:

Ojs\JournalBundle\Entity\Author:
    properties:
        translations:
            - Valid: ~
        firstName:
            - NotBlank: { groups: [submission], message: 'First name fields of authors can not be blank.' }
        lastName:
            - NotBlank: { groups: [submission], message: 'Last name fields of authors can not be blank.' }
        email:
            - NotBlank: { groups: [submission], message: 'E-mail fields of authors can not be blank.' }
            - Email: { groups: [submission] }
