Ojs\JournalBundle\Entity\IssueFileTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\IssueFile:
    properties:
        translations:
            - Valid: ~
        file:
            - NotBlank: ~
        type:
            - NotBlank: ~
        langCode:
            - NotBlank: ~
        version:
            - Type: integer
