Vipa\JournalBundle\Entity\IssueTranslation:
  properties:
    title:
      - NotBlank: ~

Vipa\JournalBundle\Entity\Issue:
    properties:
        translations:
            - Valid: ~
        year:
            - NotBlank: ~
        number:
            - Regex: '/[0-9-]+/'
        volume:
            - Regex: '/[0-9-]+/'
