Ojs\JournalBundle\Entity\JournalPostTranslation:
  properties:
    title:
      - NotBlank: ~
    content:
      - NotBlank: ~

Ojs\JournalBundle\Entity\JournalPost:
    properties:
        translations:
            - Valid: ~
