Ojs\JournalBundle\Entity\SectionTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Section:
    properties:
        translations:
            - Valid: ~
        sectionOrder:
            - NotBlank: ~
