Vipa\JournalBundle\Entity\ArticleTypes:
  checkUse:
    - { entityName: 'VipaJournalBundle:Article', field: articleType}

Vipa\JournalBundle\Entity\PersonTitle:
  checkUse:
    - { entityName: 'VipaJournalBundle:JournalContact', field: title}
    - { entityName: 'VipaUserBundle:User', field: title}

Vipa\JournalBundle\Entity\PublisherTheme:
  checkUse:
    - { entityName: 'VipaJournalBundle:Publisher', field: theme}

Vipa\JournalBundle\Entity\PublisherDesign:
  checkUse:
    - { entityName: 'VipaJournalBundle:Publisher', field: design}

Vipa\JournalBundle\Entity\Index:
  checkUse:
    - { entityName: 'VipaJournalBundle:JournalIndex', field: index}

Vipa\JournalBundle\Entity\PublisherTypes:
  checkUse:
    - { entityName: 'VipaJournalBundle:Publisher', field: publisherType}
    - { entityName: 'VipaJournalBundle:Institution', field: institutionType}

Vipa\JournalBundle\Entity\JournalTheme:
  checkUse:
    - { entityName: 'VipaJournalBundle:Journal', field: theme}

Vipa\JournalBundle\Entity\ContactTypes:
  checkUse:
    - { entityName: 'VipaJournalBundle:JournalContact', field: contactType}

Vipa\JournalBundle\Entity\Board:
  checkUse:
    - { entityName: 'VipaJournalBundle:BoardMember', field: board}

Vipa\JournalBundle\Entity\Lang:
  checkUse:
    - { entityName: 'VipaJournalBundle:Journal', field: mandatoryLang}
    - { entityName: 'VipaJournalBundle:Journal', field: languages, type: m2m}
    - { entityName: 'VipaJournalBundle:Article', field: languages, type: m2m}

Vipa\JournalBundle\Entity\Period:
  checkUse:
    - { entityName: 'VipaJournalBundle:Journal', field: periods, type: m2m}

Vipa\JournalBundle\Entity\Subject:
  checkUse:
    - { entityName: 'VipaJournalBundle:Journal', field: subjects, type: m2m}
    - { entityName: 'VipaJournalBundle:Article', field: subjects, type: m2m}
    - { entityName: 'VipaUserBundle:User', field: subjects, type: m2m}
    - { entityName: 'VipaJournalBundle:Subject', field: parent}

Vipa\JournalBundle\Entity\Institution:
  checkUse:
    - { entityName: 'VipaJournalBundle:Author', field: institution}
    - { entityName: 'VipaJournalBundle:JournalContact', field: institution}
    - { entityName: 'VipaJournalBundle:Institution', field: parent}

Vipa\JournalBundle\Entity\Section:
  checkUse:
    - { entityName: 'VipaJournalBundle:Article', field: section}
    - { entityName: 'VipaJournalBundle:Issue', field: sections, type: m2m}

Vipa\JournalBundle\Entity\ArticleFile:
  preDelete:
    - { entityName: 'VipaAnalyticsBundle:ArticleFileStatistic', field: 'articleFile' }

Vipa\JournalBundle\Entity\IssueFile:
  preDelete:
    - { entityName: 'VipaAnalyticsBundle:IssueFileStatistic', field: 'issueFile' }

Vipa\JournalBundle\Entity\Article:
  preDelete:
    - { entityName: 'VipaAnalyticsBundle:ArticleStatistic', field: 'article' }

Vipa\JournalBundle\Entity\Issue:
  preDelete:
    - { entityName: 'VipaAnalyticsBundle:IssueStatistic', field: 'issue' }

Vipa\JournalBundle\Entity\Publisher:
  checkUse:
    - { entityName: 'VipaJournalBundle:Journal', field: publisher}
    - { entityName: 'VipaJournalBundle:Publisher', field: parent}
  preDelete:
    - { entityName: 'VipaJournalBundle:PublisherTheme', field: publisher}
    - { entityName: 'VipaJournalBundle:PublisherDesign', field: publisher}
    - { entityName: 'VipaAdminBundle:PublisherManagers', field: publisher}
