knp_gaufrette:
  stream_wrapper: ~
  adapters:
    publisher:
      local:
        directory: "%kernel.root_dir%/../web/uploads/publisher"
        create: true
    publisher_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/publisher/croped"
        create: true
    institution:
      local:
        directory: "%kernel.root_dir%/../web/uploads/institution"
        create: true
    institution_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/institution/croped"
        create: true
    announcement:
      local:
        directory: "%kernel.root_dir%/../web/uploads/announcement"
        create: true
    announcement_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/announcement/croped"
        create: true
    journal:
      local:
        directory: "%kernel.root_dir%/../web/uploads/journal"
        create: true
    journal_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/journal/croped"
        create: true
    index:
      local:
        directory: "%kernel.root_dir%/../web/uploads/index"
        create: true
    index_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/index/croped"
        create: true
    user:
      local:
        directory: "%kernel.root_dir%/../web/uploads/user"
        create: true
    user_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/user/croped"
        create: true
    issue:
      local:
        directory: "%kernel.root_dir%/../web/uploads/issue"
        create: true
    issuefiles:
      local:
        directory: "%kernel.root_dir%/../web/uploads/issuefiles"
        create: true
    article:
      local:
        directory: "%kernel.root_dir%/../web/uploads/article"
        create: true
    article_croped:
      local:
        directory: "%kernel.root_dir%/../web/uploads/article/croped"
        create: true
    articlefiles:
      local:
        directory: "%kernel.root_dir%/../web/uploads/articlefiles"
        create: true
    submissionfiles:
      local:
        directory: "%kernel.root_dir%/../web/uploads/submissionfiles"
        create: true
    files:
      local:
        directory: "%kernel.root_dir%/../web/uploads/files"
        create: true
  filesystems:
    publisher:
      adapter: publisher
      alias: publisher_filesystem
    publisher_croped:
      adapter: publisher_croped
      alias: publisher_croped_filesystem
    institution:
      adapter: institution
      alias: institution_filesystem
    institution_croped:
      adapter: institution_croped
      alias: institution_croped_filesystem
    announcement:
      adapter: announcement
      alias: announcement_filesystem
    announcement_croped:
      adapter: announcement_croped
      alias: announcement_croped_filesystem
    journal:
      adapter: journal
      alias: journal_filesystem
    journal_croped:
      adapter: journal_croped
      alias: journal_croped_filesystem
    index:
      adapter: index
      alias: index_filesystem
    index_croped:
      adapter: index_croped
      alias: index_croped_filesystem
    user:
      adapter: user
      alias: user_filesystem
    user_croped:
      adapter: user_croped
      alias: user_filesystem
    issue:
      adapter: issue
      alias: issue_filesystem
    issuefiles:
      adapter: issuefiles
      alias: issuefiles_filesystem
    article:
      adapter: article
      alias: article_filesystem
    article_croped:
      adapter: article_croped
      alias: article_croped_filesystem
    articlefiles:
      adapter: articlefiles
      alias: articlefiles_filesystem
    submissionfiles:
      adapter: submissionfiles
      alias: submissionfiles_filesystem
    files:
      adapter: files
      alias: files_filesystem
oneup_uploader:
  mappings:
    generic:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['multipart/x-zip','application/zip','application/x-zip-compressed','application/x-compressed','text/plain','application/pdf','image/jpeg','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel','image/png','image/svg+xml' ]
    user:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.user_filesystem
        stream_wrapper: gaufrette://user/
    publisher:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.publisher_filesystem
        stream_wrapper: gaufrette://publisher/
    institution:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.institution_filesystem
        stream_wrapper: gaufrette://institution/
    announcement:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.announcement_filesystem
        stream_wrapper: gaufrette://announcement/
    journal:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.journal_filesystem
        stream_wrapper: gaufrette://journal/
    journalCompeting:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel' ,'image/jpeg','image/png','image/svg+xml']
      storage:
        type: gaufrette
        filesystem: gaufrette.journal_filesystem
        stream_wrapper: gaufrette://journal/
    index:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.index_filesystem
        stream_wrapper: gaufrette://index/
    issue:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.issue_filesystem
        stream_wrapper: gaufrette://issue/
    issuefiles:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel']
      storage:
        type: gaufrette
        filesystem: gaufrette.issuefiles_filesystem
        stream_wrapper: gaufrette://issuefiles/
    article:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['image/jpeg','image/png','image/svg+xml' ]
      storage:
        type: gaufrette
        filesystem: gaufrette.article_filesystem
        stream_wrapper: gaufrette://article/
    articlefiles:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['multipart/x-zip','application/zip','application/x-zip-compressed','application/x-compressed','text/plain','application/x-latex','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel','image/jpeg','image/png','image/svg+xml','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/xml']
      storage:
        type: gaufrette
        filesystem: gaufrette.articlefiles_filesystem
        stream_wrapper: gaufrette://articlefiles/
    submissionfiles:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['multipart/x-zip','application/zip','application/x-zip-compressed','application/x-compressed','text/plain','application/x-latex','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel','image/jpeg','image/png','image/svg+xml','application/vnd.openxmlformats-officedocument.presentationml.presentation']
      storage:
        type: gaufrette
        filesystem: gaufrette.submissionfiles_filesystem
        stream_wrapper: gaufrette://submissionfiles/
    files:
      enable_progress: true
      frontend: blueimp
      allowed_mimetypes: ['multipart/x-zip','application/zip','application/x-zip-compressed','application/x-compressed','text/plain','application/x-latex','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.ms-excel','image/jpeg','image/png','image/svg+xml','application/vnd.openxmlformats-officedocument.presentationml.presentation']
      storage:
        type: gaufrette
        filesystem: gaufrette.files_filesystem
        stream_wrapper: gaufrette://files/
liip_imagine:
  data_loader: stream.journal_filesystem
  loaders:
    stream.publisher_filesystem:
      stream:
        wrapper: gaufrette://publisher/
    stream.publisher_croped_filesystem:
      stream:
        wrapper: gaufrette://publisher_croped/
    stream.institution_filesystem:
      stream:
        wrapper: gaufrette://institution/
    stream.institution_croped_filesystem:
      stream:
        wrapper: gaufrette://institution_croped/
    stream.announcement_filesystem:
      stream:
        wrapper: gaufrette://announcement/
    stream.announcement_croped_filesystem:
      stream:
        wrapper: gaufrette://announcement_croped/
    stream.journal_filesystem:
      stream:
        wrapper: gaufrette://journal/
    stream.journal_croped_filesystem:
      stream:
        wrapper: gaufrette://journal_croped/
    stream.index_filesystem:
      stream:
        wrapper: gaufrette://index/
    stream.index_croped_filesystem:
      stream:
        wrapper: gaufrette://index_croped/
    stream.user_filesystem:
      stream:
        wrapper: gaufrette://user/
    stream.user_croped_filesystem:
      stream:
        wrapper: gaufrette://user_croped/
    stream.article_filesystem:
      stream:
        wrapper: gaufrette://article/
    stream.article_croped_filesystem:
      stream:
        wrapper: gaufrette://article_croped/
  resolvers:
    default:
      web_path: ~

  filter_sets:
    original: ~
    cache: ~
    journal_original:
      data_loader: stream.journal_filesystem
      quality: 90
    journal_croped:
      data_loader: stream.journal_croped_filesystem
      quality: 90
    publisher_original:
      data_loader: stream.publisher_filesystem
      quality: 90
    publisher_croped:
      data_loader: stream.publisher_croped_filesystem
      quality: 90
    institution_original:
      data_loader: stream.institution_filesystem
      quality: 90
    institution_croped:
      data_loader: stream.institution_croped_filesystem
      quality: 90
    announcement_original:
      data_loader: stream.announcement_filesystem
      quality: 90
    announcement_croped:
      data_loader: stream.announcement_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 120 }
        crop: {start:[0,0], size: [120, 120]}
    index_original:
      data_loader: stream.index_filesystem
      quality: 90
    index_croped:
      data_loader: stream.index_croped_filesystem
      quality: 90
    user_original:
      data_loader: stream.user_filesystem
      quality: 90
    user_croped:
      data_loader: stream.user_croped_filesystem
      quality: 90
    article_original:
      data_loader: stream.article_filesystem
      quality: 90
    article_croped:
      data_loader: stream.article_croped_filesystem
      quality: 90
    avatar_thumb:
      data_loader: stream.user_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 200 }
        crop: {start:[0,0], size: [200, 200]}
    issue_cover:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
          relative_resize: {  widen: 75 }
          crop: {start:[0,0], size: [75, 75]}
    issue_header:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 960 }
        crop: {start:[0,0], size: [960, 200]}
    journal_cover:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
        thumbnail: {size: [190,284], mode: outbound}
    journal_header:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 960 }
        crop: {start:[0,0], size: [960, 200]}
    journal_logo:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
        thumbnail: { size: [96, 128], mode: outbound }
    index_logo:
      data_loader: stream.index_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 200 }
        crop: {start:[0,0], size: [200, 200]}
    publisher_logo:
      data_loader: stream.publisher_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 200 }
        crop: {start:[0,0], size: [200, 200]}
    publisher_header:
      data_loader: stream.publisher_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 960 }
        crop: {start:[0,0], size: [960, 200]}
    institution_logo:
      data_loader: stream.institution_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 200 }
        crop: {start:[0,0], size: [200, 200]}
    institution_header:
      data_loader: stream.institution_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 960 }
        crop: {start:[0,0], size: [960, 200]}
    article_header:
      data_loader: stream.article_croped_filesystem
      quality: 90
      filters:
        relative_resize: {  widen: 960 }
        crop: {start:[0,0], size: [960, 200]}
    issue_cover_medium:
      data_loader: stream.journal_croped_filesystem
      quality: 90
      filters:
        relative_resize: { widen: 180}


jb_file_uploader:
  resolvers:
    journal:
      assets:
        directory: uploads/journal
    journal_croped:
      assets:
        directory: uploads/journal/croped
    publisher:
      assets:
        directory: uploads/publisher
    publisher_croped:
      assets:
        directory: uploads/publisher/croped
    institution:
      assets:
        directory: uploads/institution
    institution_croped:
      assets:
        directory: uploads/institution/croped
    announcement:
      assets:
        directory: uploads/announcement
    announcement_croped:
      assets:
        directory: uploads/announcement/croped
    index:
      assets:
        directory: uploads/index
    index_croped:
      assets:
        directory: uploads/index/croped
    user:
      assets:
        directory: uploads/user
    user_croped:
      assets:
        directory: uploads/user/croped
    journalCompeting:
      assets:
        directory: uploads/journal
    issue:
      assets:
        directory: uploads/issue
    issuefiles:
      assets:
        directory: uploads/issuefiles
    article:
      assets:
        directory: uploads/article
    article_croped:
      assets:
        directory: uploads/article/croped
    articlefiles:
      assets:
        directory: uploads/articlefiles
    submissionfiles:
      assets:
        directory: uploads/submissionfiles
    files:
      assets:
        directory: uploads/files
  endpoints:
    issue:
      upload_resolver: issue
    issuefiles:
      upload_resolver: issuefiles
    journalCompeting:
      upload_resolver: journalCompeting
    journal:
      upload_resolver: journal
      croped_resolver: journal_croped
      croped_fs: journal_croped
      upload_validators: {}
      crop_validators: {}
    publisher:
      upload_resolver: publisher
      croped_resolver: publisher_croped
      croped_fs: publisher_croped
      upload_validators: {}
      crop_validators: {}
    institution:
      upload_resolver: institution
      croped_resolver: institution_croped
      croped_fs: institution_croped
      upload_validators: {}
      crop_validators: {}
    announcement:
      upload_resolver: announcement
      croped_resolver: announcement_croped
      croped_fs: announcement_croped
      upload_validators: {}
      crop_validators: {}
    index:
      upload_resolver: index
      croped_resolver: index_croped
      croped_fs: index_croped
      upload_validators: {}
      crop_validators: {}
    user:
      upload_resolver: user
      croped_resolver: user_croped
      croped_fs: user_croped
      upload_validators: {}
      crop_validators: {}
    article:
      upload_resolver: article
      croped_resolver: article_croped
      croped_fs: article_croped
      upload_validators: {}
      crop_validators: {}
    articlefiles:
      upload_resolver: articlefiles
    submissionfiles:
      upload_resolver: submissionfiles
    files:
      upload_resolver: files

parameters:
  jb_fileuploader.resolver.asset.prototype.class: Vipa\CoreBundle\Service\FileUploadResolver\AssetsResolver
  jb_fileuploader.file_history.manager.class: Vipa\CoreBundle\Service\FileHistoryManager
  jb_fileuploader.croper.class: Vipa\CoreBundle\Service\Croper
  jb_fileuploader.crop.manager.class: Vipa\CoreBundle\Service\CropFileManager
  oneup_uploader.namer.uniqid.class : Vipa\CoreBundle\Service\FileNamer\UniqidNamer
  oneup_uploader.routing.loader.class : Vipa\CoreBundle\Service\Routing\RouteLoader