app_extra:
  resource: .
  type: advanced_extra

journal_publisher_hosting:
  prefix: /
  resource: '@OjsSiteBundle/Resources/config/routing/hosting.yml'
  condition: 'not (context.getHost() matches "/%base_host%/")'

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

vipa_admin:
  resource: '@OjsAdminBundle/Resources/config/routing.yml'
  prefix: admin
  requirements:
    id: \d+

vipa_admin_root:
  resource: '@OjsAdminBundle/Resources/config/routing_root.yml'
  prefix:   /

vipa_oai:
  resource: '@OjsOAIBundle/Resources/config/routing.yml'
  prefix: /api/public/oai

vipa_journal:
  resource: '@OjsJournalBundle/Resources/config/routing.yml'
  prefix:   /
  requirements:
    id: \d+
    publisherId: \d+
    journalId: \d+

vipa_core:
  resource: '@OjsCoreBundle/Resources/config/routing.yml'
  prefix:   /

vipa_journal_panel:
  resource: '@OjsJournalBundle/Resources/config/routing_panel.yml'
  prefix: /journal
  requirements:
    id:           \d+
    publisherId:  \d+
    journalId:    \d+
    articleId:    \d+
    issueId:      \d+
    boardId:      \d+

auth:
  resource: '@OjsUserBundle/Resources/config/routing.yml'
  prefix:   /

vipa_user:
  resource: '@OjsUserBundle/Controller/'
  type: annotation

vipa_location:
  resource: '@BulutYazilimLocationBundle/Resources/config/routing.yml'
  prefix:   /

vipa_export:
  resource: '@OjsExportBundle/Resources/config/routing.yml'
  prefix:   /

oneup_uploader:
  resource: .
  type: uploader

_liip_imagine:
  resource: '@LiipImagineBundle/Resources/config/routing.xml'
  prefix:   /

change_locale:
  path: '/locale/{code}'
  defaults:
    _controller: 'OjsJournalBundle:Common:changeLocale'

fos_js_routing:
  resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

jb_fileupload_crop:
  resource: '@JbFileUploaderBundle/Resources/config/routing.yml'

vipa_site:
  resource: '@OjsSiteBundle/Resources/config/routing.yml'
  prefix:   /

fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'

JMSTranslationBundle_ui:
  resource: "@JMSTranslationBundle/Controller/"
  type:     annotation
  prefix:   /_trans

rest:
  type: rest
  resource: routing_rest.yml
  prefix: /api/
