vipa_api_doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /public/v1/doc

vipa_api_home:
    resource: "@VipaApiBundle/Resources/config/routing.yml"
    prefix:   /
    
vipa_rest:
  type: rest
  resource: "@VipaApiBundle/Resources/config/routing_rest.yml"
  requirements:
    id:           \d+
    publisherId:  \d+
    journalId:    \d+
    articleId:    \d+
    issueId:      \d+
    boardId:      \d+
    sectionId:    \d+