security:
  encoders:
    Ojs\UserBundle\Entity\User:
      algorithm: bcrypt
    FOS\UserBundle\Model\UserInterface: bcrypt
  acl:
    connection: default
    cache:
      id:     security.acl.cache.doctrine
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
    ROLE_SUPER_ADMIN:  [ROLE_ADMIN]
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username_email
  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_home:
      pattern: /api/public/*
      stateless: true
      security: false
      anonymous: true
    api_stats:
      pattern: /api/v1/stats/*
      stateless: true
      security: false
      anonymous: true
    api:
      pattern: ^/api/
      stateless: true
      security: true
      provider: fos_userbundle
      anonymous: true
      simple_preauth:
        authenticator: apikey_authenticator
    main:
      switch_user: {parameter: _su}
      pattern: ^/
      anonymous: true
      provider: fos_userbundle
      form_login:
        login_path: /login
        check_path: /login_check
        always_use_default_target_path: false
        csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
        default_target_path: /login-redirect
      logout:
        path: /logout
        target: /
      security: true
      anonymous: true
      oauth:
        resource_owners:
          orcid: /oauth/login/check-orcid
          academicid: /oauth/login/check-academicid
          linkedin: /oauth/login/check-linkedin
        login_path:   /login
        use_forward:  false
        oauth_user_provider:
          service: vipa.user.oauth

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/user_create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/journal, roles: IS_AUTHENTICATED_FULLY }
    - { path: /manager, roles: [IS_AUTHENTICATED_FULLY] }
    - { path: /user/forgot_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /user, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/author, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/editor, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/*, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/suggest, roles: IS_AUTHENTICATED_FULLY }
    - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
