services:
  analytics.listener:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@request_stack"
    class: Vipa\AnalyticsBundle\Listener\AnalyticsSubscriber
    tags:
      -
        name: kernel.event_subscriber

  api_key_user_provider:
    arguments:
      - "@doctrine.orm.default_entity_manager"
    class: Vipa\ApiBundle\Security\ApiKeyUserProvider

  apikey_authenticator:
    arguments:
      - "@api_key_user_provider"
    class: Vipa\ApiBundle\Security\ApiKeyAuthenticator

  form.type.journal_user:
    class: Vipa\JournalBundle\Form\Type\JournalUserType
    tags:
      -
        alias: vipa_journalbundle_journaluser
        name: form.type

  gedmo.listener.softdeleteable:
    calls:
      -
        - setAnnotationReader
        -
          - "@annotation_reader"
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
      -
        connection: default
        name: doctrine.event_subscriber

  vipa.twig.common_extension:
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@liip_imagine.filter.manager"
    class: Vipa\SiteBundle\Twig\CommonExtension
    tags:
      -
        name: twig.extension

  vipa.user_provider.username_email:
    arguments:
      - "@doctrine.orm.entity_manager"
    class: Vipa\UserBundle\Service\EmailUserProvider

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      -
        name: twig.extension

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      -
        name: twig.extension

  fos_user.doctrine_registry:
     alias: doctrine