parameters:
  problematic.acl_manager.class: Vipa\CoreBundle\Acl\AclChainManager
  security.acl.dbal.provider.class: Vipa\CoreBundle\Acl\Dbal\MutableAclProvider
  security.acl.security_identity_retrieval_strategy.class: Vipa\CoreBundle\Acl\SecurityIdentityRetrievalStrategy
  security.acl.object_identity_retrieval_strategy.class: Vipa\CoreBundle\Acl\ObjectIdentityRetrievalStrategy
  vipa_core.sitemap.listener.class: Vipa\CoreBundle\EventListener\SitemapListener
  prezent_doctrine_translatable.listener.class: Vipa\CoreBundle\EventListener\TranslatableCacheListener

services:
  app.routing_loader:
    class: Vipa\CoreBundle\Routing\ThirdPartyRouteLoader
    arguments: ["@kernel", "@file_locator"]
    tags:
      - { name: routing.loader }

  security.authorization_checker:
    class: Vipa\CoreBundle\Acl\AuthorizationChecker
    arguments:
      - "@security.token_storage"
      - "@security.authentication.manager"
      - "@security.access.decision_manager"
      - "%security.access.always_authenticate_before_granting%"

  security.acl.security_identity_retrieval_strategy:
    class: "%security.acl.security_identity_retrieval_strategy.class%"
    arguments: ["@security.role_hierarchy", "@security.authentication.trust_resolver", "@vipa.journal_service"]

  vipa_mailer:
    class: Vipa\CoreBundle\Service\Mailer
    arguments:
      - "@mailer"
      - "%system_email%"
      - "%mailer_name%"
      - "@doctrine"
      - "@security.token_storage"
      - "%locale%"
      - "@translator"
      - "%prevent_mail_merge%"

  vipa_locale.locale_listener:
    class: Vipa\CoreBundle\Service\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
      - { name: kernel.event_subscriber }

  vipa_core.kernel_request_listener:
    class: Vipa\CoreBundle\Service\KernelRequestListener
    tags:
      - { name: kernel.event_subscriber }

  vipa_core.kernel_request_attr_loader:
    class: Vipa\CoreBundle\Service\RequestAttrLoaderListener
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }

  vipa.twig.vipa_extension:
    class: Vipa\CoreBundle\Service\Twig\VipaExtension
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@translator"
      - "@vipa.journal_service"
      - "@security.token_storage"
      - "@session"
      - "@request_stack"
      - "@event_dispatcher"
    tags:
      - { name: twig.extension }

  vipa.twig.display_extension:
    class: Vipa\CoreBundle\Service\Twig\DisplayExtension
    arguments:
      - "@translator"
      - "@annotation_reader"
      - "@liip_imagine.twig.extension"
    tags:
      - { name: twig.extension }

  vipa.twig.field_display_extension:
    class: Vipa\CoreBundle\Service\Twig\FieldDisplayExtension
    arguments:
      - "@translator"
      - "@annotation_reader"
      - "@liip_imagine.twig.extension"
      - "@router"
    tags:
      - { name: twig.extension }

  vipa.twig.action_extension:
    class: Vipa\CoreBundle\Service\Twig\ActionExtension
    arguments:
      - "@translator"
    tags:
      - { name: twig.extension }

  vipa.article_service:
    class: Vipa\CoreBundle\Service\ArticleService
    arguments: [ "@doctrine.orm.entity_manager","@vipa.journal_service", "@session" ]

  vipa.alice.provider:
    class: Vipa\CoreBundle\Service\AliceDataProvider
    arguments: [ "%defaultPublisherSlug%", "%system_email%" ]
    tags:
      -  { name: h4cc_alice_fixtures.provider }

  grid_action:
    class: Vipa\CoreBundle\Service\GridAction
    arguments: ["@security.csrf.token_manager", "@translator"]

  form.type.tags:
    class: Vipa\CoreBundle\Form\Type\TagsType
    arguments: [ "@router", "@translator" ]
    tags:
      - { name: form.type, alias: tags }

  form.type.journal_based_translations:
    class: Vipa\CoreBundle\Form\Type\JournalBasedTranslationsType
    arguments: [ "@vipa.journal_service"]
    tags:
      - { name: form.type }

  form.type.journal_lang_code_type:
    class: Vipa\CoreBundle\Form\Type\JournalLangCodeType
    arguments: [ "@vipa.journal_service"]
    tags:
      - { name: form.type }

  form.type.extended_entity:
      class: Vipa\CoreBundle\Form\Type\ExtendedEntityType
      arguments: ["@property_accessor"]
      tags:
          - { name: form.type, alias: extended_entity }

  form.type.purified_textarea:
      class: Vipa\CoreBundle\Form\Type\PurifiedTextareaType
      tags:
        - { name: form.type, alias: purified_textarea }

  vipa_core.sample.object_loader:
      class: Vipa\CoreBundle\Service\SampleObjectLoader
      arguments:
        - '@h4cc_alice_fixtures.manager'
        - '@doctrine.orm.entity_manager'
        - '%locale%'

  vipa_core.search_manager:
    class: Vipa\CoreBundle\Service\Search\SearchManager
    arguments: ["@translator", "@router", "@request_stack", "@vipa_core.search.native_query_generator", "@service_container"]

  vipa_core.search.native_query_generator:
    class: Vipa\CoreBundle\Service\Search\NativeQueryGenerator
    arguments: []

  vipa_core.listener.elastica_bundle:
      class: Vipa\CoreBundle\Service\Search\ElasticaTransformListener
      tags:
          - { name: kernel.event_subscriber }

  vipa_api_handler_helper:
    class: Vipa\CoreBundle\Service\ApiHandlerHelper
    arguments: ['@kernel', '@annotation_reader', '@liip_imagine.twig.extension', '@request_stack']

  kernel.listener.command_dispatch:
    class: Vipa\CoreBundle\EventListener\ConsoleExceptionListener
    arguments:
      logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: console.exception }

  core.event_listener:
    class: Vipa\CoreBundle\EventListener\CoreEventListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@vipa_mailer"]
    tags:
      - { name: kernel.event_subscriber }

  core.acl_fixer:
    class: Vipa\CoreBundle\Service\AclFixer
    arguments: ["@doctrine", "@problematic.acl_manager"]

  vipa_core.delete.service:
    class: Vipa\CoreBundle\Service\DeleteService
    arguments: ["@doctrine", "@annotation_reader", "@translator", %kernel.root_dir%, %kernel.bundles%]

  vipa_core.sitemap.listener:
    class: "%vipa_core.sitemap.listener.class%"
    arguments: ["@router", "@doctrine.orm.entity_manager"]
    tags: [{name: "presta.sitemap.listener"}]

  app.exception_listener:
    class: Vipa\CoreBundle\Listeners\ExceptionListener
    arguments: ["@router", "@session", "@translator", "@request_stack"]
    tags:
        - { name: kernel.event_listener, event: kernel.exception }

  #Look {http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/caching.html}
  file_cache:
      class: Doctrine\Common\Cache\FilesystemCache
      arguments: ['%kernel.cache_dir%']

  array_cache:
      class: Doctrine\Common\Cache\ArrayCache

  vipa_core.mail.event_chain:
    class: Vipa\CoreBundle\Events\Chain\MailEventChain

  vipa_core.core_events:
    class: Vipa\CoreBundle\Events\CoreEvents
    tags:
      - { name: vipa.mail.event}

  vipa_core.twig_events:
    class: Vipa\CoreBundle\Events\TwigEvents

  vipa.session.storage.dynamic_domain:
      class: Vipa\CoreBundle\Service\DynamicDomainSessionStorage
