ojs_apply_journal:
  path: /journal
  defaults: { _controller: "%ojs_site.application_controller.class%:journal" }

ojs_apply_publisher:
  path: /publisher
  defaults: { _controller: "OjsSiteBundle:Application:publisher" }

ojs_apply_institute_success:
  path: /publisher/success
  defaults: { _controller: "OjsSiteBundle:Application:instituteSuccess" }

ojs_apply_journal_success:
  path: /journal/success
  defaults: { _controller: "OjsSiteBundle:Application:journalSuccess" }
