Ojs\JournalBundle\Entity\Citation:
  type: entity
  table: citation
  repositoryClass: Ojs\JournalBundle\Entity\CitationRepository
  manyToMany:
    articles:
      targetEntity: Article
      mappedBy: citations
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    raw:
      type: text
      nullable: true
      gedmo:
        - versioned
    type:
      type: string
      nullable: true
      length: 20
      gedmo:
        - versioned
    orderNum:
      type: integer
      nullable: true
      column: order_num
      gedmo:
        - versioned
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: date
      nullable: true
    createdBy:
      type: string
      gedmo:
        blameable:
          on: create
    updatedBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: update
  gedmo:
   soft_deleteable:
     field_name: deletedAt
     time_aware: false
   loggable: true
  lifecycleCallbacks: {  }
