Ojs\JournalBundle\Entity\ContactTypesTranslation:
    type: entity
    table: contact_types_translations
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: TRUE
