Vipa\JournalBundle\Entity\JournalSubmissionFile:
    type: entity
    table: journal_submission_file
    repositoryClass: Vipa\JournalBundle\Entity\JournalSubmissionFileRepository
    manyToOne:
      journal:
        targetEntity: Vipa\JournalBundle\Entity\Journal
        joinColumn:
          referencedColumnName: id
          name: journal_id
        inversedBy: journalSubmissionFiles
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
      id:
        type: integer
        id: true
        generator:
          strategy: AUTO
    fields:
      title:
        type: string
        gedmo:
            - versioned
      locale:
        type: string
        nullable: true
      detail:
        type: text
        nullable: true
        gedmo:
            - versioned
      visible:
        type: boolean
        nullable: true
      required:
        type: boolean
        nullable: true
      file:
        type: string
        length: 255
        nullable: TRUE
        gedmo:
          - versioned
      deletedAt:
        type: datetime
        nullable: true
    gedmo:
      loggable: true
      soft_deleteable:
        field_name: deletedAt
