Vipa\JournalBundle\Entity\JournalSetupProgress:
    type: entity
    table: journal_setup_progress
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        journal:
            targetEntity: Journal
            joinColumn:
                name: journal_id
                referencedColumnName: id
        user:
            targetEntity: Vipa\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    fields:
        currentStep:
            type: integer
            column: current_step
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
            nullable: true
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
           nullable: true
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
           nullable: true
    lifecycleCallbacks: {  }
    gedmo:
        loggable: true
