Ojs\JournalBundle\Entity\JournalIndex:
  type: entity
  table: journal_index
  repositoryClass: Ojs\JournalBundle\Entity\JournalIndexRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    link:
      type: text
      gedmo:
          - versioned
    verified:
      type: boolean
  manyToOne:
    journal:
      targetEntity: Ojs\JournalBundle\Entity\Journal
      inversedBy: journalIndexs
      joinColumn:
        name: journal_id
        referencedColumnName: id
    index:
      targetEntity: Ojs\JournalBundle\Entity\Index
      joinColumn:
        name: index_id
        referencedColumnName: id
  gedmo:
      loggable: true
