Vipa\JournalBundle\Entity\Numerator:
    type: entity
    table: numerator
    repositoryClass: Vipa\JournalBundle\Entity\NumeratorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        journal:
            targetEntity: Vipa\JournalBundle\Entity\Journal
            joinColumn:
                name: journal_id
                referencedColumnName: id
    fields:
        type:
            type: string
            length: 255
        last:
            type: integer

    uniqueConstraints:
        journal_type_idx:
            columns: journal_id, type
    lifecycleCallbacks: {  }
