Ojs\JournalBundle\Entity\Period:
    type: entity
    table: period
    repositoryClass: Ojs\JournalBundle\Entity\PeriodRepository
    cache:
      usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
            gedmo:
              timestampable:
                on: create
        updated:
            type: datetime
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: date
            nullable: true
        createdBy:
           type: string
           gedmo:
             blameable:
               on: create
        updatedBy:
           type: string
           gedmo:
             blameable:
               on: update
    gedmo:
        loggable: true
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
    lifecycleCallbacks: {  }

