Ojs\JournalBundle\Entity\PersonTitleTranslation:
    type: entity
    table: person_title_translations
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255