Ojs\JournalBundle\Entity\PublisherTypesTranslation:
    type: entity
    table: publisher_types_translations
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true

