Vipa\JournalBundle\Entity\PublisherTranslation:
    type: entity
    table: publisher_translations
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        about:
            type: text
            nullable: true
