Vipa\JournalBundle\Entity\SectionTranslation:
    type: entity
    table: section_translations
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
