Vipa\JournalBundle\Entity\SubmissionChecklist:
  type: entity
  repositoryClass: Vipa\JournalBundle\Entity\SubmissionChecklistRepository
  table: submission_checklist
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    label:
      type: string
      gedmo:
          - versioned
    locale:
      type: string
      nullable: true
    detail:
      type: text
      nullable: true
      gedmo:
          - versioned
    visible:
      type: boolean
      nullable: true
    deletedAt:
      type: datetime
      nullable: true
    order:
      type: integer
      column: list_order
      nullable: true
      gedmo:
          - versioned
  manyToOne:
    journal:
      targetEntity: Vipa\JournalBundle\Entity\Journal
      joinColumn:
        referencedColumnName: id
        name: journal_id
      inversedBy: submissionChecklist
  gedmo:
    loggable: true
    soft_deleteable:
      field_name: deletedAt
