Ojs\JournalBundle\Entity\SubmissionSettingTranslation:
  type: entity
  table: submission_setting_translations
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
      submissionConfirmText:
          type: text
          nullable: true
      submissionAbstractTemplate:
          nullable: true
          type: text
      submissionCloseText:
          nullable: true
          type: text
