ojs_publisher_manager_design_index:
    path:  /
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:index" }

ojs_publisher_manager_design_show:
    path:  /{id}/show
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:show" }

ojs_publisher_manager_design_new:
    path:  /new
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:new" }

ojs_publisher_manager_design_create:
    path:  /create
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:create" }
    methods: [POST]

ojs_publisher_manager_design_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:edit" }

ojs_publisher_manager_design_update:
    path:  /{id}/update
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:update" }
    methods:  [PUT]

ojs_publisher_manager_design_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherDesign:delete" }
    methods:  [DELETE]
