vipa_publisher_manager_design_index:
    path:  /
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:index" }

vipa_publisher_manager_design_show:
    path:  /{id}/show
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:show" }

vipa_publisher_manager_design_new:
    path:  /new
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:new" }

vipa_publisher_manager_design_create:
    path:  /create
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:create" }
    methods: [POST]

vipa_publisher_manager_design_edit:
    path:  /{id}/edit
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:edit" }

vipa_publisher_manager_design_update:
    path:  /{id}/update
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:update" }
    methods:  [PUT]

vipa_publisher_manager_design_delete:
    path:  /{id}/delete
    defaults: { _controller: "VipaJournalBundle:ManagerPublisherDesign:delete" }
    methods:  [DELETE]
