ojs_publisher_manager_edit:
    path:  /edit
    defaults: { _controller: "OjsJournalBundle:ManagerPublisher:edit" }

ojs_publisher_manager_update:
    path:  /update
    defaults: { _controller: "OjsJournalBundle:ManagerPublisher:update" }
    methods:  [PUT]

publisher_theme:
    resource: "@OjsJournalBundle/Resources/config/routing/publisher/theme.yml"
    prefix:   /theme

publisher_design:
    resource: "@OjsJournalBundle/Resources/config/routing/publisher/design.yml"
    prefix:   /design