ojs_publisher_manager_theme_index:
    path:  /
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:index" }

ojs_publisher_manager_theme_show:
    path:  /{id}/show
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:show" }

ojs_publisher_manager_theme_new:
    path:  /new
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:new" }

ojs_publisher_manager_theme_create:
    path:  /create
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:create" }
    methods: [POST]

ojs_publisher_manager_theme_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:edit" }

ojs_publisher_manager_theme_update:
    path:  /{id}/update
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:update" }
    methods:  [PUT]

ojs_publisher_manager_theme_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsJournalBundle:ManagerPublisherTheme:delete" }
    methods:  [DELETE]
