Ojs\AnalyticsBundle\Entity\ArticleStatistic:
    type: entity
    repositoryClass: Ojs\AnalyticsBundle\Entity\ArticleStatisticRepository
    lifecycleCallbacks: {  }
    manyToOne:
        article:
            targetEntity: Ojs\JournalBundle\Entity\Article
            inversedBy: statistics
            joinColumn:
                name: article_id
                referencedColumnName: id
    fields:
        view:
            type: integer
