Ojs\AnalyticsBundle\Entity\ArticleFileStatistic:
    type: entity
    repositoryClass: Ojs\AnalyticsBundle\Entity\ArticleFileStatisticRepository
    lifecycleCallbacks: {  }
    manyToOne:
        articleFile:
            targetEntity: Ojs\JournalBundle\Entity\ArticleFile
            inversedBy: statistics
            joinColumn:
                name: article_file_id
                referencedColumnName: id
    fields:
        download:
            type: integer
