ojs_oai_homepage:
    path: /
    defaults: { _controller: "OjsOAIBundle:Default:index" }

ojs_oai_identify:
    path: /?verb=Identify
    defaults: { _controller: "OjsOAIBundle:Default:identify" }

ojs_oai_list_records:
    path: /?verb=ListRecords
    defaults: { _controller: "OjsOAIBundle:Default:records" }

ojs_oai_list_sets:
    path: /?verb=ListSets
    defaults: { _controller: "OjsOAIBundle:Default:listSets" }

ojs_oai_list_metadata_formats:
    path: /?verb=ListMetadataFormats
    defaults: { _controller: "OjsOAIBundle:Default:listMetadataFormats" }

ojs_oai_list_identifiers:
    path: /?verb=ListIdentifiers
    defaults: { _controller: "OjsOAIBundle:Default:listIdentifier" }
    
ojs_oai_journal_homepage:
    path: '/{slug}/'
    defaults: { _controller: "OjsOAIBundle:Journal:index" }

ojs_oai_journal_identify:
    path: '/{slug}/?verb=Identify'
    defaults: { _controller: "OjsOAIBundle:Journal:identify" }

ojs_oai_journal_list_records:
    path: '/{slug}/?verb=ListRecords'
    defaults: { _controller: "OjsOAIBundle:Journal:records" }

ojs_oai_journal_list_sets:
    path: '/{slug}/?verb=ListSets'
    defaults: { _controller: "OjsOAIBundle:Journal:listSets" }

ojs_oai_journal_list_metadata_formats:
    path: '/{slug}/?verb=ListMetadataFormats'
    defaults: { _controller: "OjsOAIBundle:Journal:listMetadataFormats" }

ojs_oai_journal_list_identifiers:
    path: '/{slug}/?verb=ListIdentifiers'
    defaults: { _controller: "OjsOAIBundle:Journal:listIdentifier" }
