vipa_oai_homepage:
    path: /
    defaults: { _controller: "VipaOAIBundle:Default:index" }

vipa_oai_identify:
    path: /?verb=Identify
    defaults: { _controller: "VipaOAIBundle:Default:identify" }

vipa_oai_list_records:
    path: /?verb=ListRecords
    defaults: { _controller: "VipaOAIBundle:Default:records" }

vipa_oai_list_sets:
    path: /?verb=ListSets
    defaults: { _controller: "VipaOAIBundle:Default:listSets" }

vipa_oai_list_metadata_formats:
    path: /?verb=ListMetadataFormats
    defaults: { _controller: "VipaOAIBundle:Default:listMetadataFormats" }

vipa_oai_list_identifiers:
    path: /?verb=ListIdentifiers
    defaults: { _controller: "VipaOAIBundle:Default:listIdentifier" }
    
vipa_oai_journal_homepage:
    path: '/{slug}/'
    defaults: { _controller: "VipaOAIBundle:Journal:index" }

vipa_oai_journal_identify:
    path: '/{slug}/?verb=Identify'
    defaults: { _controller: "VipaOAIBundle:Journal:identify" }

vipa_oai_journal_list_records:
    path: '/{slug}/?verb=ListRecords'
    defaults: { _controller: "VipaOAIBundle:Journal:records" }

vipa_oai_journal_list_sets:
    path: '/{slug}/?verb=ListSets'
    defaults: { _controller: "VipaOAIBundle:Journal:listSets" }

vipa_oai_journal_list_metadata_formats:
    path: '/{slug}/?verb=ListMetadataFormats'
    defaults: { _controller: "VipaOAIBundle:Journal:listMetadataFormats" }

vipa_oai_journal_list_identifiers:
    path: '/{slug}/?verb=ListIdentifiers'
    defaults: { _controller: "VipaOAIBundle:Journal:listIdentifier" }
