Ojs\AdminBundle\Entity\AdminFile:
    type: entity
    table: admin_file
    repositoryClass: Ojs\AdminBundle\Entity\AdminFileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        path:
            type: text
        size:
            type: string
            length: 255
        tags:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
