Vipa\AdminBundle\Entity\AdminJournalTheme:
  type: entity
  table: admin_journal_theme
  repositoryClass: Vipa\AdminBundle\Entity\AdminJournalThemeRepository
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    css:
      type: text
      nullable: true
      gedmo:
        - versioned
    public:
      column: is_public
      type: boolean
      nullable: true
      gedmo:
          - versioned
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: date
      nullable: true
    createdBy:
      type: string
      gedmo:
        blameable:
          on: create
    updatedBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: update
  gedmo:
    loggable: true
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
  lifecycleCallbacks: {  }

