Vipa\AdminBundle\Entity\SystemSetting:
  type: entity
  table: system_settings
  repositoryClass: Vipa\AdminBundle\Entity\SystemSettingRepository
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    userRegistrationActive:
      type: boolean
      nullable: true
    publisherApplicationActive:
      type: boolean
      nullable: true
    journalApplicationActive:
      type: boolean
      nullable: true
    articleSubmissionActive:
      type: boolean
      nullable: true
    systemFooterScript:
      type: text
      nullable: true
