site_shortlink_article:
    path: /a/{article}
    defaults: { _controller: "OjsSiteBundle:ShortLink:articleId"}

site_shortlink_doi:
    path: /doi/{doi}
    defaults: { _controller: "OjsSiteBundle:ShortLink:articleDoi"}
    requirements:
      doi: .+

ojs_application:
    resource: "@OjsSiteBundle/Resources/config/routing/application.yml"
    prefix: /apply

ojs_explore:
    resource: "@OjsSiteBundle/Resources/config/routing/explore.yml"
    prefix: /explore
redirect:
    path: /redirect/{type}/{id}
    defaults: { _controller: "OjsSiteBundle:Redirect:redirect" }

ojs_user_profile:
    path: /@{slug}
    host: "%base_host%"
    defaults: { _controller: "OjsSiteBundle:User:profile" }

ojs_user_edit_profile:
    path: /user/update
    host: "%base_host%"
    defaults: { _controller: "OjsSiteBundle:User:editProfile"}

ojs_user_custom_field:
    path: /user/custom_field
    defaults: { _controller: "OjsSiteBundle:User:customField"}

ojs_user_custom_field_create:
    path: /user/custom_field/create/{id}
    defaults: { _controller: "OjsSiteBundle:User:createCustomField", id: null}

ojs_user_custom_field_delete:
    path: /user/custom_field/delete/{id}
    defaults: { _controller: "OjsSiteBundle:User:deleteCustomField"}

ojs_user_connected_account:
    path: /user/connected_accounts
    defaults: { _controller: "OjsSiteBundle:User:connectedAccount" }

ojs_user_connected_account_add:
    path: /user/connected_accounts/add
    defaults: { _controller: "OjsSiteBundle:User:addConnectedAccount"}

ojs_user_connected_account_delete:
    path: /user/connected_accounts/delete/{id}
    defaults: { _controller: "OjsSiteBundle:User:deleteConnectedAccount"}

ojs_public_index:
    path:  /
    defaults: { _controller: "OjsSiteBundle:Site:index" }
    host: "%base_host%"

ojs_search:
    resource: "@OjsSiteBundle/Resources/config/routing/search.yml"

#publisher subdomain
ojs_publisher_page:
    path:  /
    defaults: { _controller: "OjsSiteBundle:Site:publisherPage" }

ojs_journal_index:
    path:  /{slug}
    defaults: { _controller: "OjsSiteBundle:Journal:journalIndex" }

ojs_journal_index_articles:
    path: /{slug}/articles
    defaults: { _controller: "OjsSiteBundle:Article:journalArticles" }

ojs_journal_index_board:
    path: /{slug}/board
    defaults: { _controller: "OjsSiteBundle:Journal:journalBoard" }

ojs_site_journal_page:
    path: /{journal_slug}/page/{slug}
    defaults: { _controller: "OjsSiteBundle:JournalCms:journalPageDetail" }

ojs_site_journal_post:
    path: /{journal_slug}/post/{slug}
    defaults: { _controller: "OjsSiteBundle:JournalCms:journalPostDetail" }

ojs_last_articles_index:
    path:  /{slug}/last
    defaults: { _controller: "OjsSiteBundle:Journal:lastArticlesIndex" }

ojs_archive_index:
    path:  /{slug}/archive
    defaults: { _controller: "OjsSiteBundle:Journal:archiveIndex" }

ojs_early_preview_index:
    path:  /{slug}/early_preview
    defaults: { _controller: "OjsSiteBundle:Journal:earlyPreviewIndex" }

ojs_announcement_index:
    path:  /{slug}/announcements
    defaults: { _controller: "OjsSiteBundle:JournalCms:announcementIndex" }

ojs_journal_subscribe:
    path:  /{slug}/subscribe
    defaults: { _controller: "OjsSiteBundle:Journal:subscribe" }

ojs_issue_page:
    path: /{journal_slug}/issue/{id}
    defaults: { _controller: "OjsSiteBundle:Issue:issuePage" }
    requirements:
        id: '\d+'

ojs_article_page:
    path:  /{slug}/issue/{issue_id}/{article_id}
    defaults: { _controller: "OjsSiteBundle:Article:articlePage", issue_id: null}

ojs_article_withoutIssue_page:
    path:  /{slug}/article/{article_id}
    defaults: { _controller: "OjsSiteBundle:Article:articleWithoutIssuePage"}

ojs_journal_contacts:
    path: /{slug}/contacts
    defaults: { _controller: "OjsSiteBundle:Journal:journalContacts" }

ojs_people:
    resource: "@OjsSiteBundle/Resources/config/routing/people.yml"
    prefix: /explore/people

ojs_site_download:
    prefix:   /download
    resource: '@OjsSiteBundle/Resources/config/routing/download.yml'

ojs_site_cms:
    resource: '@OjsSiteBundle/Resources/config/routing/cms.yml'

ojs_journal_lockss:
    resource: '@OjsSiteBundle/Resources/config/routing/lockss.yml'
