site_shortlink_article:
    path: /a/{article}
    defaults: { _controller: "VipaSiteBundle:ShortLink:articleId"}

site_shortlink_doi:
    path: /doi/{doi}
    defaults: { _controller: "VipaSiteBundle:ShortLink:articleDoi"}
    requirements:
      doi: .+

vipa_application:
    resource: "@VipaSiteBundle/Resources/config/routing/application.yml"
    prefix: /apply

vipa_explore:
    resource: "@VipaSiteBundle/Resources/config/routing/explore.yml"
    prefix: /explore
redirect:
    path: /redirect/{type}/{id}
    defaults: { _controller: "VipaSiteBundle:Redirect:redirect" }

vipa_user_profile:
    path: /@{slug}
    host: "%base_host%"
    defaults: { _controller: "VipaSiteBundle:User:profile" }

vipa_user_edit_profile:
    path: /user/update
    host: "%base_host%"
    defaults: { _controller: "VipaSiteBundle:User:editProfile"}

vipa_user_custom_field:
    path: /user/custom_field
    defaults: { _controller: "VipaSiteBundle:User:customField"}

vipa_user_custom_field_create:
    path: /user/custom_field/create/{id}
    defaults: { _controller: "VipaSiteBundle:User:createCustomField", id: null}

vipa_user_custom_field_delete:
    path: /user/custom_field/delete/{id}
    defaults: { _controller: "VipaSiteBundle:User:deleteCustomField"}

vipa_user_connected_account:
    path: /user/connected_accounts
    defaults: { _controller: "VipaSiteBundle:User:connectedAccount" }

vipa_user_connected_account_add:
    path: /user/connected_accounts/add
    defaults: { _controller: "VipaSiteBundle:User:addConnectedAccount"}

vipa_user_connected_account_delete:
    path: /user/connected_accounts/delete/{id}
    defaults: { _controller: "VipaSiteBundle:User:deleteConnectedAccount"}

vipa_public_index:
    path:  /
    defaults: { _controller: "VipaSiteBundle:Site:index" }
    host: "%base_host%"

vipa_search:
    resource: "@VipaSiteBundle/Resources/config/routing/search.yml"

#publisher subdomain
vipa_publisher_page:
    path:  /
    defaults: { _controller: "VipaSiteBundle:Site:publisherPage" }

vipa_journal_index:
    path:  /{slug}
    defaults: { _controller: "VipaSiteBundle:Journal:journalIndex" }

vipa_journal_index_articles:
    path: /{slug}/articles
    defaults: { _controller: "VipaSiteBundle:Article:journalArticles" }

vipa_journal_index_board:
    path: /{slug}/board
    defaults: { _controller: "VipaSiteBundle:Journal:journalBoard" }

vipa_site_journal_page:
    path: /{journal_slug}/page/{slug}
    defaults: { _controller: "VipaSiteBundle:JournalCms:journalPageDetail" }

vipa_site_journal_post:
    path: /{journal_slug}/post/{slug}
    defaults: { _controller: "VipaSiteBundle:JournalCms:journalPostDetail" }

vipa_last_articles_index:
    path:  /{slug}/last
    defaults: { _controller: "VipaSiteBundle:Journal:lastArticlesIndex" }

vipa_archive_index:
    path:  /{slug}/archive
    defaults: { _controller: "VipaSiteBundle:Journal:archiveIndex" }

vipa_early_preview_index:
    path:  /{slug}/early_preview
    defaults: { _controller: "VipaSiteBundle:Journal:earlyPreviewIndex" }

vipa_announcement_index:
    path:  /{slug}/announcements
    defaults: { _controller: "VipaSiteBundle:JournalCms:announcementIndex" }

vipa_journal_subscribe:
    path:  /{slug}/subscribe
    defaults: { _controller: "VipaSiteBundle:Journal:subscribe" }

vipa_issue_page:
    path: /{journal_slug}/issue/{id}
    defaults: { _controller: "VipaSiteBundle:Issue:issuePage" }
    requirements:
        id: '\d+'

vipa_article_page:
    path:  /{slug}/issue/{issue_id}/{article_id}
    defaults: { _controller: "VipaSiteBundle:Article:articlePage", issue_id: null}

vipa_article_withoutIssue_page:
    path:  /{slug}/article/{article_id}
    defaults: { _controller: "VipaSiteBundle:Article:articleWithoutIssuePage"}

vipa_journal_contacts:
    path: /{slug}/contacts
    defaults: { _controller: "VipaSiteBundle:Journal:journalContacts" }

vipa_people:
    resource: "@VipaSiteBundle/Resources/config/routing/people.yml"
    prefix: /explore/people

vipa_site_download:
    prefix:   /download
    resource: '@VipaSiteBundle/Resources/config/routing/download.yml'

vipa_site_cms:
    resource: '@VipaSiteBundle/Resources/config/routing/cms.yml'

vipa_journal_lockss:
    resource: '@VipaSiteBundle/Resources/config/routing/lockss.yml'
