Vipa\UserBundle\Entity\MultipleMail:
    type: entity
    table: multiple_mail
    repositoryClass: Vipa\UserBundle\Entity\MultipleMailRepository
    id:
        id:
          type: integer
          length: null
          unique: false
          nullable: false
          precision: 0
          id: true
          generator:
              strategy: IDENTITY
    fields:
        mail:
          type: string
          length: 255
          unique: true
          nullable: false
        activationCode:
          type: string
          length: 255
          unique: false
          nullable: true
        isConfirmed:
          type: boolean
          nullable: true
    manyToOne:
        user:
          targetEntity: Vipa\UserBundle\Entity\User
          joinColumn:
            name: user_id
            referencedColumnName: id
          inversedBy: multipleMails
    gedmo:
        loggable: true
    lifecycleCallbacks: {  }
