Ojs\UserBundle\Entity\UserOauthAccount:
  type: entity
  table: user_oauth_accounts
  repositoryClass: Ojs\UserBundle\Entity\UserOauthAccountRepository
  id:
    id:
      generator:
        strategy: AUTO
      id: true
      type: integer
  fields:
    provider:
      type: string
      length: 255
    providerId:
      type: string
    token:
      type: string
      nullable: true
  manyToOne:
    user:
      targetEntity: Ojs\UserBundle\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: id
      inversedBy: oauthAccounts
      cascade: ['persist']
  gedmo:
    loggable: true
  lifecycleCallbacks: {  }
