vipa_admin_journal_theme_index:
    path:  /
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:index" }

vipa_admin_journal_theme_show:
    path:  /{id}/show
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:show" }

vipa_admin_journal_theme_new:
    path:  /new
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:new" }

vipa_admin_journal_theme_create:
    path:  /create
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:create" }
    methods: [POST]

vipa_admin_journal_theme_edit:
    path:  /{id}/edit
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:edit" }

vipa_admin_journal_theme_update:
    path:  /{id}/update
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:update" }
    methods:  [PUT]

vipa_admin_journal_theme_delete:
    path:  /{id}/delete
    defaults: { _controller: "VipaAdminBundle:AdminJournalTheme:delete" }
    methods:  [DELETE]
