ojs_admin_application_file_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:index"}

ojs_admin_application_file_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:show"}

ojs_admin_application_file_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:new"}

ojs_admin_application_file_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:create"}
    methods:  POST

ojs_admin_application_file_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:edit"}

ojs_admin_application_file_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:update"}
    methods: [PUT]

ojs_admin_application_file_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminJournalApplicationFile:delete"}
    methods: [DELETE]
