vipa_admin_file_index:
    path:     /
    defaults: { _controller: "VipaAdminBundle:AdminFile:index" }

vipa_admin_file_show:
    path:     /{id}/show
    defaults: { _controller: "VipaAdminBundle:AdminFile:show" }

vipa_admin_file_new:
    path:     /new
    defaults: { _controller: "VipaAdminBundle:AdminFile:new" }

vipa_admin_file_create:
    path:     /create
    defaults: { _controller: "VipaAdminBundle:AdminFile:create" }
    methods:  POST

vipa_admin_file_edit:
    path:     /{id}/edit
    defaults: { _controller: "VipaAdminBundle:AdminFile:edit" }

vipa_admin_file_update:
    path:     /{id}/update
    defaults: { _controller: "VipaAdminBundle:AdminFile:update" }
    methods:  [POST, PUT]

vipa_admin_file_delete:
    path:     /{id}/delete
    defaults: { _controller: "VipaAdminBundle:AdminFile:delete" }
    methods:  [POST, DELETE]
