ojs_admin_journal_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminJournal:index" }

ojs_admin_journal_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminJournal:show" }

ojs_admin_journal_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminJournal:new" }

ojs_admin_journal_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminJournal:create" }
    methods: [POST]

ojs_admin_journal_edit:
    path:  /{id}/edit
    defaults: { _controller: "%ojs_admin.journal_controller.class%:edit" }

ojs_admin_journal_update:
    path:  /{id}/update
    defaults: { _controller: "%ojs_admin.journal_controller.class%:update" }
    methods:  [PUT]

ojs_admin_journal_autocomplete:
    path:  /autocomplete
    defaults: { _controller: "OjsAdminBundle:AdminJournal:autoComplete" }
    methods:  [GET]
