ojs_admin_mail_template_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminMailTemplate:index" }

ojs_admin_mail_template_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminMailTemplate:show" }

ojs_admin_mail_template_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminMailTemplate:edit" }

ojs_admin_mail_template_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminMailTemplate:update" }
    methods:  [PUT]
