ojs_admin_period_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:index" }

ojs_admin_period_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:show" }

ojs_admin_period_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:new" }

ojs_admin_period_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:create" }
    methods: [POST]

ojs_admin_period_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:edit" }

ojs_admin_period_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:update" }
    methods: [POST,PUT]

ojs_admin_period_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminPeriod:delete" }
