ojs_admin_person_title_index:
    path:     /
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:index" }

ojs_admin_person_title_show:
    path:     /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:show" }

ojs_admin_person_title_new:
    path:     /new
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:new" }

ojs_admin_person_title_create:
    path:     /create
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:create" }
    methods:  POST

ojs_admin_person_title_edit:
    path:     /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:edit" }

ojs_admin_person_title_update:
    path:     /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:update" }
    methods:  [POST, PUT]

ojs_admin_person_title_delete:
    path:     /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminPersonTitle:delete" }
    methods:  [POST, DELETE]
