vipa_admin_post_index:
    path:     /
    defaults: { _controller: "VipaAdminBundle:AdminPost:index" }

vipa_admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "VipaAdminBundle:AdminPost:show" }

vipa_admin_post_new:
    path:     /new
    defaults: { _controller: "VipaAdminBundle:AdminPost:new" }

vipa_admin_post_create:
    path:     /create
    defaults: { _controller: "VipaAdminBundle:AdminPost:create" }
    methods: [POST]

vipa_admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "VipaAdminBundle:AdminPost:edit" }

vipa_admin_post_update:
    path:     /{id}/update
    defaults: { _controller: "VipaAdminBundle:AdminPost:update" }
    methods: [POST,PUT]

vipa_admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "VipaAdminBundle:AdminPost:delete" }
