vipa_admin_publisher_type_index:
    path:  /
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:index" }

vipa_admin_publisher_type_show:
    path:  /{id}/show
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:show" }

vipa_admin_publisher_type_new:
    path:  /new
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:new" }

vipa_admin_publisher_type_create:
    path:  /create
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:create" }
    methods: [POST]

vipa_admin_publisher_type_edit:
    path:  /{id}/edit
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:edit" }

vipa_admin_publisher_type_update:
    path:  /{id}/update
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:update" }
    methods:  [PUT]

vipa_admin_publisher_type_delete:
    path:  /{id}/delete
    defaults: { _controller: "VipaAdminBundle:AdminPublisherType:delete" }
    methods:  [DELETE]
