ojs_admin_publisher_managers_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:index" }

ojs_admin_publisher_managers_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:show" }

ojs_admin_publisher_managers_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:new" }

ojs_admin_publisher_managers_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:create" }
    methods: [POST]

ojs_admin_publisher_managers_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:edit" }

ojs_admin_publisher_managers_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:update" }
    methods:  [PUT]

ojs_admin_publisher_managers_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminPublisherManagers:delete" }
    methods:  [DELETE]
