vipa_admin_application_publisher_index:
  path:     /publisher
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:index" }

vipa_admin_application_publisher_show:
  path:     /publisher/{id}
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:detail" }

vipa_admin_application_publisher_edit:
  path:     /publisher/{id}/edit
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:edit" }

vipa_admin_application_publisher_update:
  path:     /publisher/{id}/update
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:update" }
  methods:  [PUT]

vipa_admin_application_publisher_delete:
  path:     /publisher/{id}/delete
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:delete" }
  methods:  [DELETE]

vipa_admin_application_publisher_save:
  path:  /publisher/{id}/save
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:save" }

vipa_admin_application_publisher_reject:
  path:  /publisher/{id}/reject
  defaults: { _controller: "VipaAdminBundle:AdminPublisherApplication:reject" }