ojs_admin_publisher_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:index" }

ojs_admin_publisher_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:show" }

ojs_admin_publisher_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:new" }

ojs_admin_publisher_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:create" }
    methods: [POST]

ojs_admin_publisher_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:edit" }

ojs_admin_publisher_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:update" }
    methods:  [PUT]

ojs_admin_publisher_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminPublisher:delete" }
    methods:  [DELETE]
