ojs_admin_publisher_design_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:index" }

ojs_admin_publisher_design_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:show" }

ojs_admin_publisher_design_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:new" }

ojs_admin_publisher_design_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:create" }
    methods: [POST]

ojs_admin_publisher_design_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:edit" }

ojs_admin_publisher_design_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:update" }
    methods:  [PUT]

ojs_admin_publisher_design_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminPublisherDesign:delete" }
    methods:  [DELETE]
