vipa_journal_announcement_index:
    path:     /{journalId}/announcement
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:index" }

vipa_journal_announcement_new:
    path:     /{journalId}/announcement/new
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:new" }

vipa_journal_announcement_create:
    path:     /{journalId}/announcement/create
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:create" }
    methods:  [POST]

vipa_journal_announcement_show:
    path:     /{journalId}/announcement/{id}/show
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:show" }

vipa_journal_announcement_edit:
    path:     /{journalId}/announcement/{id}/edit
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:edit" }

vipa_journal_announcement_update:
    path:     /{journalId}/announcement/{id}/update
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:update" }
    methods:  [PUT]

vipa_journal_announcement_delete:
    path:     /{journalId}/announcement/{id}/delete
    defaults: { _controller: "VipaJournalBundle:JournalAnnouncement:delete" }
    methods:  [DELETE]