ojs_journal_design_index:
    path:     /{journalId}/design/
    defaults: { _controller: "OjsJournalBundle:Design:index" }

ojs_journal_design_show:
    path:     /{journalId}/design/{id}/show
    defaults: { _controller: "OjsJournalBundle:Design:show" }

ojs_journal_design_new:
    path:     /{journalId}/design/new
    defaults: { _controller: "OjsJournalBundle:Design:new" }

ojs_journal_design_create:
    path:     /{journalId}/design/create
    defaults: { _controller: "OjsJournalBundle:Design:create" }
    methods: [POST]

ojs_journal_design_edit:
    path:     /{journalId}/design/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Design:edit" }

ojs_journal_design_update:
    path:     /{journalId}/design/{id}/update
    defaults: { _controller: "OjsJournalBundle:Design:update" }
    methods: [PUT]

ojs_journal_design_delete:
    path:     /{journalId}/design/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Design:delete" }
    methods: [DELETE]
