ojs_journal_file_index:
    path:     /{journalId}/file/
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:index" }

ojs_journal_file_show:
    path:     /{journalId}/file/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:show" }

ojs_journal_file_new:
    path:     /{journalId}/file/new
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:new" }

ojs_journal_file_create:
    path:     /{journalId}/file/create
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:create" }
    methods:  POST

ojs_journal_file_edit:
    path:     /{journalId}/file/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:edit" }

ojs_journal_file_update:
    path:     /{journalId}/file/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:update" }
    methods: [PUT]

ojs_journal_file_delete:
    path:     /{journalId}/file/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalSubmissionFile:delete" }
    methods: [DELETE]
