vipa_journal_journal_contact_index:
    path:  /{journalId}/contact/
    defaults: { _controller: "VipaJournalBundle:JournalContact:index" }

vipa_journal_journal_contact_sort:
    path:     /{journalId}/contact/sort
    defaults: { _controller: "VipaJournalBundle:JournalContact:sort" }

vipa_journal_journal_contact_show:
    path:  /{journalId}/contact/{id}/show
    defaults: { _controller: "VipaJournalBundle:JournalContact:show" }

vipa_journal_journal_contact_new:
    path:  /{journalId}/contact/new
    defaults: { _controller: "VipaJournalBundle:JournalContact:new" }

vipa_journal_journal_contact_create:
    path:  /{journalId}/contact/create
    defaults: { _controller: "VipaJournalBundle:JournalContact:create" }
    methods: [POST]

vipa_journal_journal_contact_edit:
    path:  /{journalId}/contact/{id}/edit
    defaults: { _controller: "VipaJournalBundle:JournalContact:edit" }

vipa_journal_journal_contact_update:
    path:  /{journalId}/contact/{id}/update
    defaults: { _controller: "VipaJournalBundle:JournalContact:update" }
    methods: [PUT]

vipa_journal_journal_contact_delete:
    path:  /{journalId}/contact/{id}/delete
    defaults: { _controller: "VipaJournalBundle:JournalContact:delete" }
    methods: [DELETE]
