ojs_journal_mail_template_index:
    path:     /{journalId}/mail-template/
    defaults: { _controller: "OjsJournalBundle:MailTemplate:index" }

ojs_journal_mail_template_show:
    path:     /{journalId}/mail-template/{id}/show
    defaults: { _controller: "OjsJournalBundle:MailTemplate:show" }

ojs_journal_mail_template_edit:
    path:     /{journalId}/mail-template/{id}/edit
    defaults: { _controller: "OjsJournalBundle:MailTemplate:edit" }

ojs_journal_mail_template_update:
    path:     /{journalId}/mail-template/{id}/update
    defaults: { _controller: "OjsJournalBundle:MailTemplate:update" }
    methods: [PUT]
