ojs_journal_settings_index:
    path:  /{journalId}/settings/
    defaults: { _controller: "OjsJournalBundle:Manager:journalSettings" }

ojs_journal_settings_update:
    path:  /{journalId}/settings/update
    defaults: { _controller: "OjsJournalBundle:Manager:updateJournal" }
    methods:  [PUT, POST]

ojs_article_types_settings_index:
    path:  /{journalId}/settings/article-types
    defaults: { _controller: "OjsJournalBundle:Manager:ArticleTypesSettings" }

ojs_article_types_settings_update:
    path:  /{journalId}/settings/article-types/update
    defaults: { _controller: "OjsJournalBundle:Manager:updateArticleTypes" }
    methods:  [PUT, POST]

ojs_journal_settings_submission:
    path:  /{journalId}/settings/submission
    defaults: { _controller: "OjsJournalBundle:SubmissionSetting:edit" }
