\Vipa\UserBundle\Entity\User:
  user_author:
    username (unique): demo_author
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Author
    lastName: Demo
    email (unique): demo.author@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_grammer_editor:
    username (unique): user_demo_grammer_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Grammer
    lastName: Editor
    email (unique): user_demo_grammer_editor@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_spelling_editor:
    username (unique): user_demo_spelling_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Spelling
    lastName: Editor
    email (unique): user_demo_spelling_editor@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_section_editor:
    username (unique): user_demo_section_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Section
    lastName: Editor
    email (unique): user_demo_section_editor@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_reviewer:
    username (unique): user_demo_reviewer
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Reviewer
    lastName: Reviewer
    email (unique): user_demo_reviewer@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_layout_editor:
    username (unique): user_demo_layout_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Layout
    lastName: Editor
    email (unique): user_demo_layout_editor@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_copy_editor:
    username (unique): user_demo_copy_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Copy
    lastName: Editor
    email (unique): user_demo_copy_editor@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_proof_reader:
    username (unique): user_demo_proof_reader
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Proof
    lastName: Reader
    email (unique): user_demo_proof_reader@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_demo_secretary:
    username (unique): user_demo_secretary
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Secretary
    lastName: Secretary
    email (unique): user_demo_secretary@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
    title: 1
    tags: <text(20)>, <text(10)>
  user_journal_manager:
    username (unique): demo_journal_manager
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Journal Manager
    lastName: Demo
    email (unique): demo.manager@vipa.io
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    title: 1
    tags: <text(20)>, <text(10)>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
  user_demo_tester:
    username (unique): demo_journal_tester
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Journal Tester
    lastName: Demo
    email (unique): demo.tester@vipa.io
    apikey (unique): 'NTg3YjljYmYzZDA0MDZjMWY4MTlkOTYwMWQyZmNlMTYwMzU0NjY0Yw=='
    title: 1
    tags: <text(20)>, <text(10)>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
  user_demo_editor:
    username (unique): demo_editor
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: Journal Editor
    lastName: Demo
    email (unique): demo.editor@vipa.io
    apikey (unique): 'NTg3HjluYmSzZDE0MDZyMWY4ITlnOTMwEWQyRmNtMTYwMzU0NjY0Yw=='
    title: 1
    tags: <text(20)>, <text(10)>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0
  random_user_{1..100}:
    username (unique): <userName()>
    password: '$2y$10$ToRGKh9IQHyzaQ2F6wc/N.qY2fw92soSr8Qwd5A/QWfRC.IlqFNT2'
    firstName: <firstName()>
    lastName: <lastName()>
    email (unique): <companyEmail()>
    apikey (unique): <regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}')>
    enabled: 1
    locked: 0
    expired: 0
    credentialsExpired: 0