ojs_user_oauth:
    resource: "@OjsUserBundle/Resources/config/routing/oauth.yml"
    prefix:   /oauth

confirm_email_warning:
    path:  /unconfirmed
    defaults: { _controller: "OjsUserBundle:Security:unconfirmed" }

login:
    path: /login
    host: "%base_host%"
    defaults: { _controller: "OjsUserBundle:Security:login" }

email_confirm:
    path: /confirm/email/{code}
    defaults: { _controller: "OjsUserBundle:Security:confirmEmail" }

multiplemail_confirm:
    path: /confirm/multiplemail/{code}
    defaults: { _controller: "OjsUserBundle:Security:multipleMailConfirm" }

ojs_user_multiple_mail:
    path: /user/multiple_mails
    defaults: { _controller: "OjsUserBundle:MultipleMail:multipleMail"}

ojs_user_multiple_mail_add:
    path: /user/multiple_mails/add
    defaults: { _controller: "OjsUserBundle:MultipleMail:addMultipleMail"}

ojs_user_multiple_mail_delete:
    path: /user/multiple_mail/delete/{id}
    defaults: { _controller: "OjsUserBundle:MultipleMail:deleteMultipleMail"}

logout:
    host: "%base_host%"
    path: /logout

login_check:
    path: /login_check

regenerate_apikey:
    path: /user/apikey/regenerate
    defaults: { _controller: "OjsUserBundle:UserApi:regenerateAPI" }

ojs_user_get_apikey:
    path: /user/apikey
    defaults: { _controller: "OjsUserBundle:UserApi:getApiKey" }

user_create_password:
    path: /password/create
    defaults: { _controller: "OjsUserBundle:Security:createPassword" }

ojs_user_redirect:
    path: /login-redirect
    defaults: { _controller: "OjsUserBundle:Security:redirect" }
